name: Build HEF with Hailo

on:
  workflow_dispatch:

jobs:
  build-hef:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1) Logowanie do GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: klaudia-senator
          password: ${{ secrets.GHCR_TOKEN }}

      # 2) Pull obrazu TAP-PAS
      - name: Pull Hailo TAP-PAS image
        run: |
          docker pull ghcr.io/klaudia-senator/hailo-tappas:v3.31.0

      # 3) Uruchomienie kompilacji w kontenerze
      - name: Compile ONNX to HEF
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/models:/local/workspace/models \
            -v ${{ github.workspace }}/calib_images:/local/workspace/calib_images \
            ghcr.io/klaudia-senator/hailo-tappas:v3.31.0 \
            bash -lc "
              pip install /local/workspace/models/hailo_dataflow_compiler-3.31.0-py3-none-linux_x86_64.whl &&
              git clone https://github.com/hailo-ai/hailo_model_zoo.git &&
              cd hailo_model_zoo && pip install -e . &&
              hailomz compile \
                --ckpt /local/workspace/models/model_unet.onnx \
                --hw-arch hailo8l \
                --calib-path /local/workspace/calib_images \
                --classes 80 \
                --performance
            "

      # 4) Upload gotowego HEF
      - name: Upload HEF artifact
        uses: actions/upload-artifact@v3
        with:
          name: hef-artifact
          path: models/model_unet.hef
