name: Test Upload

on: workflow_dispatch

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Create file
        run: echo "hello" > hello.txt

      - name: Upload artifact v2
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: hello.txt
